PUT http://localhost:3003/api/blogs/61a071884f332dc2dfaca8d7
Content-Type: application/json

{
    "title": "Genshin Impact",
    "author": "Do Duc Tam",
    "url": "https://genshin.mihoyo.com/en/",
    "likes" : 10
}